version: '2'
services:
    mongoDB:
        container_name: mongo11
        image: mongo:4.0.11
        volumes:
            - "./DBstorage/data/db:/data/db"
        expose:
            - 27017
        ports:
            - 27018:27017
        entrypoint: [ "/usr/bin/mongod","--bind_ip_all", "--replSet", "rs0" ]
    aiapp:
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            - DBhost=mongo11
            - DBport=27017
            - DBusername=owner
            - DBpassword=renwo
            - DBdatabase=appdb
        image: aiapp09
        expose:
            - 8080
        ports:
            - 8080:8080 
        depends_on: 
            - mongoDB

